name: Example
options:
  bundleIdPrefix: dev.jano.keychain.example
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  createIntermediateGroups: true

settings:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: NO
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    IPHONEOS_DEPLOYMENT_TARGET: 16.4
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: PPSF6CNP8Q
    CODE_SIGN_IDENTITY: Apple Development

packages:

  Keychain:
    path: ..

targets:

  Example:
    dependencies:
      - package: Keychain
    platform: iOS
    settings:
      CODE_SIGN_ENTITLEMENTS: Example.entitlements
      CURRENT_PROJECT_VERSION: 1
      INFOPLIST_FILE: Sources/Info.plist
      MARKETING_VERSION: 1.0.0
      PRODUCT_BUNDLE_IDENTIFIER: dev.jano.keychain.example
      PRODUCT_NAME: Example
    PROVISIONING_PROFILE_SPECIFIER:
    scheme:
      testTargets:
        - ExampleTests
    sources:
      - Sources
    type: application

  ExampleTests:
    dependencies:
      - target: Example
      - package: Keychain
    platform: iOS
    settings:
      INFOPLIST_FILE: Tests/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: dev.jano.keychain.example.tests
    PROVISIONING_PROFILE_SPECIFIER:
    sources:
      - Tests
    type: bundle.unit-test
